name: tpugraphs
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.0.0
  - aiohttp=3.8.6
  - aiosignal=1.3.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attrs=23.1.0
  - blinker=1.6.3
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.20.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.1
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=3.3.0
  - click=8.1.7
  - colorama=0.4.6
  - cryptography=41.0.4
  - flatbuffers=23.5.26
  - frozenlist=1.4.0
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=2.23.3
  - google-pasta=0.2.0
  - grpcio=1.54.3
  - h5py=3.10.0
  - hdf5=1.14.2
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - jax=0.4.16
  - jaxlib=0.4.14
  - keras-preprocessing=1.1.2
  - krb5=1.21.2
  - libabseil=20230125.3
  - libaec=1.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.4.0
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgrpc=1.54.3
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.24
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.43.2
  - libssh2=1.11.0
  - libzlib=1.2.13
  - llvm-openmp=17.0.2
  - markdown=3.5
  - markupsafe=2.1.3
  - ml_dtypes=0.2.0
  - multidict=6.0.4
  - ncurses=6.4
  - oauthlib=3.2.2
  - openssl=3.1.3
  - opt-einsum=3.3.0
  - opt_einsum=3.3.0
  - packaging=23.2
  - pip=23.2.1
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.12
  - python-flatbuffers=23.5.26
  - python_abi=3.10
  - pyu2f=0.1.5
  - re2=2023.03.02
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scipy=1.11.3
  - setuptools=68.2.2
  - six=1.16.0
  - snappy=1.1.10
  - termcolor=2.3.0
  - tk=8.6.13
  - tqdm=4.66.1
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=2.0.6
  - werkzeug=3.0.0
  - wheel=0.41.2
  - xz=5.2.6
  - yarl=1.9.2
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - apache-beam==2.46.0
      - cloudpickle==2.2.1
      - contextlib2==21.6.0
      - crcmod==1.7
      - dill==0.3.1.1
      - docopt==0.6.2
      - fastavro==1.8.4
      - fasteners==0.19
      - google-auth-oauthlib==0.4.6
      - google-vizier==0.1.11
      - googleapis-common-protos==1.56.4
      - greenlet==3.0.0
      - grpcio-tools==1.48.2
      - hdfs==2.7.2
      - httplib2==0.21.0
      - keras==2.11.0
      - libclang==16.0.6
      - ml-collections==0.1.1
      - networkx==3.1
      - numpy==1.24.4
      - objsize==0.6.1
      - orjson==3.9.8
      - portpicker==1.6.0
      - proto-plus==1.22.3
      - protobuf==3.19.4
      - psutil==5.9.5
      - pyarrow==9.0.0
      - pydot==1.4.2
      - pymongo==3.13.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - sqlalchemy==1.4.20
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.14.0
      - tensorflow-estimator==2.11.0
      - tensorflow-gnn==0.6.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-macos==2.11.0
      - tensorflow-ranking==0.5.3
      - wrapt==1.14.1
      - zstandard==0.21.0
